doctrine:
    dbal:
        connections:
            parallalax_blog:
              driver:   "%database_default_driver%"
              host:     "%database_default_host%"
              port:     "%database_default_port%"
              dbname:   "%database_default_name%"
              user:     "%database_default_user%"
              password: "%database_default_password%"

    orm:
        entity_managers:
            parallalax_blog:
                connection:       parallalax_blog
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    ParallalaxDashboardNewsBundle: ~
